run:
  timeout: 5m
  modules-download-mode: mod

linters:
  enable:
    - goimports
    - revive
    - govet
    - staticcheck
    - gocyclo
    - gocritic
    - gosimple
  disable:
    - errcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  goimports:
    local-prefixes: github.com/memlimit/clickhouse-cli